#!/usr/bin/env python3
"""
B^4 Trilemma Solver --- SAT-style backtracking search.

Tests whether the sub-monoid generated by {i/2, j/2} inside B^4
can admit a monotone partial order with 0 as bottom and 1 as top.

If UNSAT: no compatible monotone order exists on this (truncated)
domain, proving the trilemma for any monoid containing it.

If SAT: a compatible order exists on the truncation. Then check
whether it forms a lattice (every pair has meet and join in D).

Key validity argument: any compatible order on the full (infinite)
monoid restricts to a compatible order on any sub-domain. So if a
truncation has no compatible order, neither does the full monoid.

Author: J. Arturo Ornelas Brand
Date: 2026-04-12
"""
from fractions import Fraction
import time
import sys

# ---- Quaternion arithmetic (exact rational) ----

class Q:
    __slots__ = ('c', '_h')
    def __init__(self, r, i=0, j=0, k=0):
        self.c = (Fraction(r), Fraction(i), Fraction(j), Fraction(k))
        self._h = hash(self.c)
    def __mul__(self, o):
        a,b,c,d = self.c; e,f,g,h = o.c
        return Q(a*e-b*f-c*g-d*h, a*f+b*e+c*h-d*g,
                 a*g-b*h+c*e+d*f, a*h+b*g-c*f+d*e)
    def norm_sq(self):
        return sum(x*x for x in self.c)
    def __eq__(self, o):
        return isinstance(o, Q) and self.c == o.c
    def __hash__(self):
        return self._h
    def __repr__(self):
        r,i,j,k = self.c
        parts = []
        if r: parts.append(str(float(r)))
        if i: parts.append(f"{float(i)}i")
        if j: parts.append(f"{float(j)}j")
        if k: parts.append(f"{float(k)}k")
        return '(' + '+'.join(parts) + ')' if parts else '0'

ZERO = Q(0); ONE = Q(1)

# ---- Domain generation ----

def closure(gens, max_size=80):
    """Compute closure of {0,1} + gens under Hamilton product within B^4."""
    D = {ZERO, ONE} | set(gens)
    rnd = 0
    while True:
        elts = list(D)
        new = set()
        for x in elts:
            for y in elts:
                p = x * y
                if p not in D and p not in new and p.norm_sq() <= 1:
                    new.add(p)
        rnd += 1
        if not new:
            print(f"  Closure complete after round {rnd}: {len(D)} elements")
            break
        if len(D) + len(new) > max_size:
            print(f"  Round {rnd}: +{len(new)} would give {len(D)+len(new)} > {max_size}. Truncating.")
            break
        D |= new
        print(f"  Round {rnd}: +{len(new)} -> {len(D)} elements")
    return D

def build_tables(elts):
    """Build product table and preimage tables for constraint propagation."""
    idx = {q: i for i, q in enumerate(elts)}
    n = len(elts)
    # Product table: prod[i][j] = index of elts[i]*elts[j], or -1
    prod = [[-1]*n for _ in range(n)]
    in_count = 0
    for i in range(n):
        for j in range(n):
            p = elts[i] * elts[j]
            if p in idx:
                prod[i][j] = idx[p]
                in_count += 1
    # Left-preimage: for pair (a,b), all (z,x,y) with prod[z][x]=a, prod[z][y]=b
    left_pre = [[[] for _ in range(n)] for _ in range(n)]
    right_pre = [[[] for _ in range(n)] for _ in range(n)]
    for z in range(n):
        for x in range(n):
            zx = prod[z][x]
            if zx < 0: continue
            for y in range(n):
                zy = prod[z][y]
                if zy < 0 or zx == zy: continue
                left_pre[zx][zy].append((x, y))
        for x in range(n):
            xz = prod[x][z]
            if xz < 0: continue
            for y in range(n):
                yz = prod[y][z]
                if yz < 0 or xz == yz: continue
                right_pre[xz][yz].append((x, y))
    return prod, left_pre, right_pre, in_count

# ---- Constraint propagation + backtracking solver ----

# State: le[i][j] = True (i<=j), False (NOT i<=j), None (unknown)
# For i==j, always True (reflexivity).

class Solver:
    def __init__(self, n, prod, left_pre, right_pre, idx_zero, idx_one):
        self.n = n
        self.prod = prod
        self.left_pre = left_pre
        self.right_pre = right_pre
        self.idx0 = idx_zero
        self.idx1 = idx_one
        # Order matrix
        self.le = [[None]*n for _ in range(n)]
        for i in range(n):
            self.le[i][i] = True
        self.trail = []  # (i, j, old_val) for undo
        self.conflict = False
        self._queue = []

    def _set(self, i, j, val):
        """Set le[i][j] = val. Enqueue for propagation. Detect conflict."""
        if i == j:
            if val is False:
                self.conflict = True
            return
        cur = self.le[i][j]
        if cur is not None:
            if cur != val:
                self.conflict = True
            return
        self.trail.append((i, j, None))
        self.le[i][j] = val
        self._queue.append((i, j, val))

    def propagate(self):
        """BFS propagation: transitivity + monotonicity + contrapositives."""
        n = self.n
        prod = self.prod
        while self._queue and not self.conflict:
            i, j, val = self._queue.pop(0)
            if val:
                # --- le[i][j] = True ---
                # Antisymmetry: le[j][i] = False
                self._set(j, i, False)
                # Transitivity fwd: le[j][k]=True => le[i][k]=True
                for k in range(n):
                    if self.le[j][k] is True:
                        self._set(i, k, True)
                # Transitivity bwd: le[k][i]=True => le[k][j]=True
                for k in range(n):
                    if self.le[k][i] is True:
                        self._set(k, j, True)
                # Left mono: for all z, prod[z][i]>=0 and prod[z][j]>=0 => le[zi][zj]=True
                for z in range(n):
                    zi = prod[z][i]; zj = prod[z][j]
                    if zi >= 0 and zj >= 0:
                        self._set(zi, zj, True)
                # Right mono: for all z, prod[i][z]>=0 and prod[j][z]>=0 => le[iz][jz]=True
                for z in range(n):
                    iz = prod[i][z]; jz = prod[j][z]
                    if iz >= 0 and jz >= 0:
                        self._set(iz, jz, True)
            else:
                # --- le[i][j] = False ---
                # Transitivity contrapositive:
                #   le[i][k]=True AND le[k][j]=True => le[i][j]=True
                #   so NOT le[i][j] => for all k: NOT(le[i][k] AND le[k][j])
                #   if le[i][k]=True => le[k][j]=False
                #   if le[k][j]=True => le[i][k]=False
                for k in range(n):
                    if k != i and k != j:
                        if self.le[i][k] is True:
                            self._set(k, j, False)
                        if self.le[k][j] is True:
                            self._set(i, k, False)
                # Left mono contrapositive:
                #   le[x][y] => le[zx][zy], so NOT le[zx][zy] => NOT le[x][y]
                #   (i,j) = (zx, zy) => find all (x,y) preimages
                for (x, y) in self.left_pre[i][j]:
                    self._set(x, y, False)
                # Right mono contrapositive
                for (x, y) in self.right_pre[i][j]:
                    self._set(x, y, False)

    def checkpoint(self):
        return len(self.trail)

    def restore(self, cp):
        while len(self.trail) > cp:
            i, j, old = self.trail.pop()
            self.le[i][j] = old
        self.conflict = False
        self._queue.clear()

    def init_boundary(self):
        """0 is bottom, 1 is top."""
        for x in range(self.n):
            self._set(self.idx0, x, True)
            self._set(x, self.idx1, True)
        self.propagate()

    def count_unknowns(self):
        c = 0
        for i in range(self.n):
            for j in range(self.n):
                if i != j and self.le[i][j] is None:
                    c += 1
        return c

    def pick_unknown(self):
        """Most-constrained-variable heuristic: pick the pair (i,j) where
        i and j have the most determined relations (fewest unknowns)."""
        best = None
        best_score = -1
        for i in range(self.n):
            for j in range(self.n):
                if i != j and self.le[i][j] is None:
                    # Score: number of determined relations involving i or j
                    score = 0
                    for k in range(self.n):
                        if self.le[i][k] is not None: score += 1
                        if self.le[k][i] is not None: score += 1
                        if self.le[j][k] is not None: score += 1
                        if self.le[k][j] is not None: score += 1
                    if score > best_score:
                        best_score = score
                        best = (i, j)
        return best

    def solve(self, max_nodes=2000000):
        """Backtracking search. Returns 'SAT' or 'UNSAT' or 'TIMEOUT'."""
        self.nodes = 0
        self.start_time = time.time()

        def search():
            self.nodes += 1
            if self.nodes % 200000 == 0:
                elapsed = time.time() - self.start_time
                unk = self.count_unknowns()
                print(f"    [{elapsed:.1f}s] nodes={self.nodes}, unknowns={unk}")
            if self.nodes > max_nodes:
                return 'TIMEOUT'
            if self.conflict:
                return 'UNSAT'
            pair = self.pick_unknown()
            if pair is None:
                return 'SAT'
            i, j = pair
            # Branch: try True first (i <= j)
            cp = self.checkpoint()
            self._set(i, j, True)
            self.propagate()
            if not self.conflict:
                result = search()
                if result != 'UNSAT':
                    return result
            self.restore(cp)
            # Branch: try False (NOT i <= j)
            cp = self.checkpoint()
            self._set(i, j, False)
            self.propagate()
            if not self.conflict:
                result = search()
                if result != 'UNSAT':
                    return result
            self.restore(cp)
            return 'UNSAT'

        return search()

    def extract_order(self):
        """If SAT, extract the partial order as a list of (i,j) with i < j."""
        pairs = []
        for i in range(self.n):
            for j in range(self.n):
                if i != j and self.le[i][j] is True:
                    pairs.append((i, j))
        return pairs

    def check_lattice(self, elts):
        """Check if current order forms a lattice (every pair has meet and join in D)."""
        n = self.n
        failures = []
        for x in range(n):
            for y in range(x+1, n):
                # Find meet: greatest lower bound
                lower = [z for z in range(n) if self.le[z][x] is True and self.le[z][y] is True]
                # Meet = z in lower such that all other l in lower have l <= z
                meet = None
                for z in lower:
                    if all(self.le[w][z] is True for w in lower):
                        meet = z
                        break
                if meet is None:
                    failures.append(('meet', x, y, elts[x], elts[y]))
                    if len(failures) >= 5:
                        return failures
                # Find join: least upper bound
                upper = [z for z in range(n) if self.le[x][z] is True and self.le[y][z] is True]
                join = None
                for z in upper:
                    if all(self.le[z][w] is True for w in upper):
                        join = z
                        break
                if join is None:
                    failures.append(('join', x, y, elts[x], elts[y]))
                    if len(failures) >= 5:
                        return failures
        return failures


# ---- Algebraic pre-analysis ----

def algebraic_argument(elts, idx):
    """Derive forced relations algebraically before running SAT."""
    print("\n--- Algebraic pre-analysis ---")
    a = Q(0, Fraction(1,2))
    b = Q(0, 0, Fraction(1,2))
    if a not in idx or b not in idx:
        print("  Generators not in domain, skipping.")
        return
    ia, ib = idx[a], idx[b]
    ab = a * b  # k/4
    ba = b * a  # -k/4
    a2 = a * a  # -1/4
    print(f"  a = {a}  (idx {ia})")
    print(f"  b = {b}  (idx {ib})")
    print(f"  ab = {ab}  {'IN' if ab in idx else 'OUT'}")
    print(f"  ba = {ba}  {'IN' if ba in idx else 'OUT'}")
    print(f"  a^2 = {a2}  {'IN' if a2 in idx else 'OUT'}")
    print(f"  ab != ba: {ab != ba}")

    # Total order impossibility
    print("\n  Total order impossibility (algebraic):")
    print("  Suppose a < b (or b < a) in a total monotone order.")
    print("  Left-mult a<b by a: a^2 < ab, i.e., -1/4 < k/4")
    print("  Right-mult a<b by b: ab < b^2, i.e., k/4 < -1/4")
    print("  Contradiction: -1/4 < k/4 AND k/4 < -1/4.")
    print("  Similarly for b < a. So a and b MUST be incomparable.")


# ---- Main ----

def main():
    print("=" * 60)
    print("B^4 TRILEMMA SOLVER")
    print("=" * 60)

    a = Q(0, Fraction(1,2))
    b = Q(0, 0, Fraction(1,2))

    # Phase 1: Generate domain
    print("\nPhase 1: Domain generation (generators = {i/2, j/2})")
    max_sizes = [20, 40, 80]

    for max_sz in max_sizes:
        print(f"\n--- max_size = {max_sz} ---")
        D = closure([a, b], max_size=max_sz)
        elts = sorted(D, key=lambda q: (q.norm_sq(), q.c))
        n = len(elts)
        idx = {q: i for i, q in enumerate(elts)}

        print(f"\n  Domain: {n} elements")
        for i, e in enumerate(elts):
            print(f"    [{i:2d}] {e}  |q|^2={float(e.norm_sq()):.6f}")

        # Build tables
        prod, left_pre, right_pre, in_count = build_tables(elts)
        total = n * n
        pct = 100.0 * in_count / total if total else 0
        print(f"\n  Product closure: {in_count}/{total} ({pct:.1f}%) products land in D")

        # Algebraic analysis
        algebraic_argument(elts, idx)

        # Phase 2: Constraint propagation
        print(f"\nPhase 2: Constraint propagation (n={n})")
        solver = Solver(n, prod, left_pre, right_pre, idx[ZERO], idx[ONE])
        solver.init_boundary()
        if solver.conflict:
            print("  *** CONTRADICTION from boundary constraints alone! ***")
            print(f"  RESULT: UNSAT --- no monotone partial order exists on this {n}-element domain.")
            print("  The B^4 trilemma is PROVED for any monoid containing this domain.")
            return
        unk = solver.count_unknowns()
        det = n*(n-1) - unk
        print(f"  After propagation: {det} determined, {unk} unknown (of {n*(n-1)} directed pairs)")

        if unk == 0:
            print("  All pairs determined. Checking consistency...")
            print("  RESULT: SAT (propagation alone determined a valid order).")
            # Check lattice
            failures = solver.check_lattice(elts)
            if not failures:
                print("  Lattice check: PASS --- this IS a lattice order.")
                print("  *** COUNTEREXAMPLE to B^4 trilemma conjecture! ***")
            else:
                print(f"  Lattice check: FAIL --- {len(failures)} pair(s) lack meet/join.")
                for f in failures[:3]:
                    print(f"    {f[0]} missing for ({f[3]}, {f[4]})")
            continue

        # Phase 3: Backtracking search
        print(f"\nPhase 3: Backtracking search ({unk} unknowns)")
        t0 = time.time()
        result = solver.solve(max_nodes=2000000)
        elapsed = time.time() - t0
        print(f"\n  Result: {result} ({solver.nodes} nodes, {elapsed:.1f}s)")

        if result == 'UNSAT':
            print(f"  *** No monotone partial order exists on this {n}-element domain. ***")
            print("  The B^4 trilemma is PROVED for any monoid containing this domain.")
            return
        elif result == 'SAT':
            print("  A compatible monotone partial order EXISTS on this truncation.")
            # Check lattice
            failures = solver.check_lattice(elts)
            if not failures:
                print("  Lattice check: PASS")
                print("  *** COUNTEREXAMPLE to B^4 trilemma conjecture! ***")
                # Print the order
                order = solver.extract_order()
                print(f"  Order has {len(order)} relations.")
                return
            else:
                print(f"  Lattice check: FAIL ({len(failures)} pairs lack meet/join)")
                for f in failures[:3]:
                    print(f"    {f[0]} missing for ({f[3]}, {f[4]})")
                print("  Monotone order exists but is NOT a lattice.")
                print("  Trying larger domain...")
                continue
        else:
            print(f"  Search timed out at {solver.nodes} nodes.")
            print("  Trying larger domain...")
            continue

    print("\n" + "=" * 60)
    print("SUMMARY: Search exhausted all domain sizes without conclusive result.")
    print("The B^4 trilemma conjecture remains OPEN for infinite domains.")
    print("=" * 60)

if __name__ == '__main__':
    main()
